// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArAlxu0_AruyM2LKLxxr_qeEV71QQAVWs',
    appId: '1:615113923331:web:01a06eca13e838b4cda736',
    messagingSenderId: '615113923331',
    projectId: 'micro-volunteering-hub-afb21',
    authDomain: 'micro-volunteering-hub-afb21.firebaseapp.com',
    storageBucket: 'micro-volunteering-hub-afb21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnBYaLdFgYyqR7Tfvk_0SudvLRtogLbdM',
    appId: '1:615113923331:android:595a9dad177f8828cda736',
    messagingSenderId: '615113923331',
    projectId: 'micro-volunteering-hub-afb21',
    storageBucket: 'micro-volunteering-hub-afb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-UvJbeUPxVOiCQyYaaL9TN7CiAnKNPY',
    appId: '1:615113923331:ios:36404f583a82bdebcda736',
    messagingSenderId: '615113923331',
    projectId: 'micro-volunteering-hub-afb21',
    storageBucket: 'micro-volunteering-hub-afb21.firebasestorage.app',
    androidClientId: '615113923331-7si1neuaitp2q6seah3085ks5n3vuo0h.apps.googleusercontent.com',
    iosClientId: '615113923331-c7vuaupo1ptsi7j68utu5isg6s4oumfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.microVolunteeringHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-UvJbeUPxVOiCQyYaaL9TN7CiAnKNPY',
    appId: '1:615113923331:ios:36404f583a82bdebcda736',
    messagingSenderId: '615113923331',
    projectId: 'micro-volunteering-hub-afb21',
    storageBucket: 'micro-volunteering-hub-afb21.firebasestorage.app',
    androidClientId: '615113923331-7si1neuaitp2q6seah3085ks5n3vuo0h.apps.googleusercontent.com',
    iosClientId: '615113923331-c7vuaupo1ptsi7j68utu5isg6s4oumfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.microVolunteeringHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArAlxu0_AruyM2LKLxxr_qeEV71QQAVWs',
    appId: '1:615113923331:web:f00319df2c3fb5d1cda736',
    messagingSenderId: '615113923331',
    projectId: 'micro-volunteering-hub-afb21',
    authDomain: 'micro-volunteering-hub-afb21.firebaseapp.com',
    storageBucket: 'micro-volunteering-hub-afb21.firebasestorage.app',
  );

}